### ISSUE TITLE
Typify categories as expense or income categories

### ISSUE THREAD

**Issue by mtotschnig** [mtotschnig/MyExpenses#212]
Default could still be neutral

**Comment by sabi0** [comment]
+1
I don't want to look through all the Studies, Taxes, Housing, etc. to find the Salary category when registering an income.

**Comment by mtotschnig** [comment]
Another aspect of this ticket, a user made me aware of, is the following:
If you add a transaction with a negative amount for an income category, instead of counting it as an expense it could be counted as a reduction of income (and vice versa), for example if it is a refund of an earlier transaction

**Comment by klaviartur** [comment]
> Default could still be neutral

Hi Michael,
since I am the ominous user who made you aware of the necessity/perks of this feature, i will also add my thoughts to the default being neutral:

IMHO it will create a conflict between those users who just don't care and leave everything as it is (neutral) and those who want to differentiate between income/expense/neutral, because the definition of "neutral" differs between the two groups.

Instead, I would argue, there need to be four categories, each describing in which total(s) it is counted: income / expense / both / none, with "both" being the default.

Hope, this makes sense to you!

Greetings
Artur

**Comment by mtotschnig** [comment]
@klaviartur Thanks Artur for the interesting perspective. Actually, I was just thinking about how to represent transactions that represent neither expense nor income, for example a transfer of money to an account that is not managed by the app.
If I understand you correctly. a category defined as both, would have lead to positive transactions mapped to it considered income, and negative transactions considered expense. For the none category, is it also the "Transfer" use case that you have in mind, or do you see a different or additional semantics for it?

**Comment by klaviartur** [comment]
> For the none category, is it also the "Transfer" use case that you have in mind, or do you see a different or additional semantics for it?

No, you basicly nailed it ;)

**Comment by mtotschnig** [comment]
@klaviartur I am wondering if it might make sense to limit the type configuration to main categories, so that sub categories would always behave as specified by their root category. This would make configuration easier for users. Or do you think it is necessary to allow to have sub categories with different type configuration than their root?

**Comment by klaviartur** [comment]
For me personally the limitation on one type per main category is absolutely sufficient, but I don't see a reason other than a bit of extra programming work to not offer a type per subcategory.

If you wanted to implement the filtering of (sub-)categories by type, then you'd need to:
1. check every main category for its type and keep matches or proceed with steps 2 and 3 for non-matches
2. check non-matching main categories for contained matching sub-categories. if any, keep them and the main category in the tree.
3. lock the non-matching main categories, that are only there because they contain mathcing sub-categories for selection, maybe make the non-selectability visible by marking them using a font color with less contrast in respect to the background (greyed-out).

That said, I would like to point out, that filtering was not a desired feature in my original request, but instead was added by  @sabi0 . Normally I welcome every additional functionality, but in this case I see a conflict:

If filtering was implemented, the +/- switch in front of the amount would gain an extra function, not only being the sign for the amount, but also the input for the category filter. This would make it mandatory to set the sign to the desired category type, which in turn would prevent me from achieving what I initially intended: to add a negative income or a "negative" expense.

Of course, one could define the category filtering to be the single purpose of the +/- switch and force (and allow) me to input an extra minus sign in the amount to achieve the aforementioned. While I find that somewhat unintuitive I can live with that. Those "refunds" are somewhat rare (but still important) and I see the benefit of the filtering. This combinations would allow both and bring the most benefit IMHO.

Greetings
Artur

**Comment by klaviartur** [comment]
> @klaviartur I am wondering if it might make sense to limit the type configuration to main categories, so that sub categories would always behave as specified by their root category. This would make configuration easier for users. Or do you think it is necessary to allow to have sub categories with different type configuration than their root?

Make the sub-categories' type initially match the main ones by default, but make it editable to offer both: ease of configuration for the low-maintenance users and flexibility for the power users.

**Comment by klaviartur** [comment]
Personally, I don't like the current mechanic of the main category (containing sub categories) selection at all:
Long press and select.
I would prefer every main category, as soon as it has a child element, to automatically aquire an additional virtual sub-category at the top of the list which reflects/points to itself. No extra object, just for the tree view. This would make it more intuitive to select while not blowing up the data structure and still allowing mixed use of main and sub-categories.

So, instead of:

**Taxes** (main category, selectable by single tap)
**Food** (main category, selectable by long-press)
-> Take-Out (sub-category, selectable by single tap)

i would like to see

**Taxes** (main category, selectable by single tap)
**Food** (main category, non-selectable)
-> Food (virtual sub-category, reflecting the main category, selectable by single tap)
-> Take-Out (sub-category, selectable by single tap)

Feels much more intuitive.

This probably is a feature request of its own. Feel free to copy into a new one.

**Comment by mtotschnig** [comment]
@klaviartur Thanks for your input! With respect to the differentiation between the sign of the amount (+/-) and the type of the transaction (income/expense), my idea was that when the category selection screen opens, it would originally be filtered by the type that the amount would indicate, but it can easily be toggled to the opposite type by a switch in the action bar.

**Comment by mtotschnig** [comment]
@klaviartur With respect to the main category mechanic, do you know that there is already an option "Select parent category on short tap" in the overflow menu?

**Comment by mtotschnig** [comment]
I checked out two other apps that have expense and income categories (com.expensemanager and com.bluecatsoftware.financisto). Both only allow setting the type on the main category. I am inclined to follow the same solution.

**Comment by mtotschnig** [comment]
Transactions that are not mapped to any categories could either be counted as transfers or as expense/income. This will be user configurable.

**Comment by mtotschnig** [comment]
TODOS:

- [ ] Add category type to synchronization 
- [ ] Category export to synchronization
- [ ] QIF import / export?
- [ ] Category selection screen: Toggle between expense and income

**Comment by klaviartur** [comment]
> Thanks for your input! With respect to the differentiation between the sign of the amount (+/-) and the type of the transaction (income/expense), my idea was that when the category selection screen opens, it would originally be filtered by the type that the amount would indicate, but it can easily be toggled to the opposite type by a switch in the action bar.

Alright, perfectly good. M

**Comment by klaviartur** [comment]
> @klaviartur With respect to the main category mechanic, do you know that there is already an option "Select parent category on short tap" in the overflow menu?

I was not aware, thank you!
But while it seems better at first glance, after a few days of using it I see the problem for right handed people that have to stretch their thumb a lot to get to the arrows for expanding a main category.

In conclusion: I'd still prefer the solution I described earlier to replace the long press one. But that'sjust my 2ct.
