### ISSUE TITLE
Customize CSV export 

### ISSUE THREAD

**Issue by mtotschnig** [mtotschnig/MyExpenses#332]
- [x]  Allow to use only one column for amount instead of two distinct ones for income and expense
- [x] Allow to separate date to two columns (date and time)
- [x] Split category levels

**Comment by klawdhfzasjhaa** [comment]
+1. Add minus symbol for expsenses. A clear warning in the release notes should let users prepare their import scripts for Excel etc.

**Comment by Matth7878** [comment]
Please also add ability to have category and sub categories splitted => it has been changed to use ":" as a separator (before it used as expected 2 columns) and it's annoying to have to manually split it back each time there is an export. :-/
