### ISSUE TITLE
Allow customization of main menu

### ISSUE THREAD

**Issue by mtotschnig** [mtotschnig/MyExpenses#703]
Only a few items are displayed directly in the actionbar, the rest being pushed into the overflow menu. User asks for having control on which items are ordered in front, so that they are directly displayed.

**Comment by mtotschnig** [comment]
TODOS:

- [ ] deal with corrupted value in preference
- [ ] restart after reconfiguration
- [ ] persist state in configuration dialog
- [ ] add credits to sealed-enum library
- [ ] testing
