### ISSUE TITLE
Budget widget

### ISSUE THREAD

**Issue by mtotschnig** [mtotschnig/MyExpenses#726]
User should be able to configure widget to display a specific budget. It would show the allocated budget, spent amount and remainder.

**Comment by mtotschnig** [comment]
a widget that shows me my currently remaining daily budget for the remaining days of a specified period. Example: 1st day €300 budget for 30 days=ad €10/day 2nd day (after €50 purchase) €250: 29 days=ad €8.62/day 
Daily updated remaining budget display as a widget would be a great everyday help (so far only available with HEPTA for ios)

**Comment by mtotschnig** [comment]
TODOs:

- [ ] Legacy version for API < 31
- [ ] Handle click (open budget activity)
- [ ] Load data
- [ ] Format currencies
- [ ] Localize
- [ ] previewLayout
- [ ] update widget when data changes
- [ ] Budget configure: Display type of budget
